# This file will be included by the Makefile under the project directory.
makefloat:
	gcc -c -m32 -fno-builtin -o ./obj/lib-common/FLOAT.o ./lib-common/FLOAT.c

FLOAT_OBJ := $(FLOAT:.a=.o)

$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

# TODO: write a rule for generating $(FLOAT_OBJ)
